// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupRolloutPrefs.extensions.fxmonitor.enabled", true);
user_pref("app.normandy.startupRolloutPrefs.network.cookie.cookieBehavior", 4);
user_pref("app.normandy.user_id", "79af9ab4-6908-40b6-9fce-659d80f0f40d");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1565382052);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1565382022);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 80);
user_pref("browser.newtabpage.activity-stream.impressionId", "{c3f5176f-f8a5-4fe4-bcca-76d3c5233e3e}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1565382028672");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1565385628672");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1565382027");
user_pref("browser.slowStartup.averageTime", 11435);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20190517141553");
user_pref("browser.startup.homepage_override.mstone", "67.0");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1565382030633");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "67.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "78d0b36631ec4398b978890d52e40bd3");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "67.0");
user_pref("extensions.lastPlatformVersion", "67.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"a1a523d9-767f-479a-ba3d-9bc937e9430d\",\"fxmonitor@mozilla.org\":\"ac044040-5a03-4bba-9fbe-9fff9e2b6311\",\"screenshots@mozilla.org\":\"cd167d64-1bd4-484d-95f5-62dd09d8740d\",\"webcompat-reporter@mozilla.org\":\"e2dbf8a3-19fb-43af-ac3d-40961f97e3e6\",\"webcompat@mozilla.org\":\"5fdc624b-e7d7-4093-8a05-6e7b1e77e731\"}");
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "2a8d385f-5d1b-48a1-86ba-fab514ea5673");
user_pref("security.sandbox.plugin.tempDirSuffix", "96617f8f-5cbc-4855-aabe-bd89d78d8cdf");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1565382015);
user_pref("toolkit.telemetry.cachedClientID", "7a0c57f4-dc30-4b3b-9824-af4f15ca7af4");
user_pref("toolkit.telemetry.previousBuildID", "20190517141553");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
